"""
Task (a): Synchronization via transition monoid BFS.

Algorithm:
    Each letter a ∈ Σ defines a transformation t_a: Q → Q where t_a(q) = τ(q, a).
    The transition monoid T_A is generated by composing these transformations.

    BFS approach:
    - Start queue with the generator transformations {t_a : a ∈ Σ}
    - For each transformation f in the queue, compute f ∘ t_a for each a ∈ Σ
    - If any resulting transformation is constant (all states map to same value), return True
    - Track visited transformations to avoid revisiting

    A transformation can be represented as a tuple (t(0), t(1), ..., t(n-1)).

WARNING: |T_A| can be up to |Q|^|Q|. Use small inputs until confident.
"""

from collections import deque
from typing import Dict, FrozenSet, List, Optional, Set, Tuple

from dfa.core import DFA, State, Letter


def _build_generators(A: DFA) -> Dict[Letter, Tuple]:
    """
    Build the generator transformations {t_a : a ∈ Σ} from a DFA.

    Each t_a is stored as a tuple indexed by sorted states:
        t_a = (τ(q_0, a), τ(q_1, a), ..., τ(q_{n-1}, a))

    Returns dict mapping letter -> transformation tuple, plus the sorted state list.
    """
    Q, Sigma, tau, _, _ = A
    states = sorted(Q)  # Fix an ordering
    generators = {}
    for a in Sigma:
        generators[a] = tuple(tau[(q, a)] for q in states)
    return generators, states


def _compose(f: Tuple, g: Tuple) -> Tuple:
    """
    Compose transformations: (f ∘ g)(q) = g(f(q)).

    Since transformations are tuples indexed by position,
    composition f then g means: for each position i, result[i] = g[f[i]].

    Note: We follow the convention that reading letter a then letter b
    means applying t_a first, then t_b. So the product t_a · t_b = t_b ∘ t_a.
    """
    # TODO: Implement
    pass


def _is_constant(t: Tuple) -> bool:
    """Check if transformation t is constant (all elements equal)."""
    # TODO: Implement
    pass


def is_synchronizing_monoid(A: DFA) -> bool:
    """
    Task (a): Test if DFA A is synchronizing by enumerating the transition monoid.

    Uses BFS over transformations. Returns True if a constant transformation
    is found in T_A, False if the entire monoid is enumerated without finding one.

    Parameters:
        A — a valid DFA 5-tuple

    Returns:
        True if A is synchronizing, False otherwise.

    Warning: Can be extremely slow for large |Q|. The monoid can contain
    up to |Q|^|Q| elements.
    """
    # TODO: Implement BFS over transition monoid
    pass
