"""
Task (a): Synchronization via transition monoid BFS.

Algorithm:
    Each letter a ∈ Σ defines a transformation t_a: Q → Q where t_a(q) = τ(q, a).
    The transition monoid T_A is generated by composing these transformations.

    BFS approach:
    - Start queue with the generator transformations {t_a : a ∈ Σ}
    - For each transformation f in the queue, compute f ∘ t_a for each a ∈ Σ
    - If any resulting transformation is constant (all states map to same value), return True
    - Track visited transformations to avoid revisiting

    A transformation can be represented as a tuple (t(0), t(1), ..., t(n-1)).

WARNING: |T_A| can be up to |Q|^|Q|. Use small inputs until confident.
"""

from collections import deque
from typing import Dict, FrozenSet, List, Optional, Set, Tuple

from dfa.core import DFA, State, Letter


def _build_generators(A: DFA) -> Dict[Letter, Tuple]:
    """
    Build the generator transformations {t_a : a ∈ Σ} from a DFA.

    Each t_a is stored as a tuple indexed by sorted states:
        t_a = (τ(q_0, a), τ(q_1, a), ..., τ(q_{n-1}, a))

    Returns dict mapping letter -> transformation tuple, plus the sorted state list.
    """
    Q, Sigma, tau, _, _ = A
    states = sorted(Q)  # Fix an ordering
    generators = {}
    for a in Sigma:
        generators[a] = tuple(tau[(q, a)] for q in states)
    return generators, states


def _compose(f: Tuple, g: Tuple, states: list, state_to_idx: dict) -> Tuple:
    """
    Compose transformations: apply f first, then g.

    Convention: reading letter a then letter b means t_b ∘ t_a.
    So compose(f, g)[i] = g[state_to_idx[f[i]]].

    f and g are tuples indexed by position in sorted states.
    f[i] is the state that states[i] maps to under f.
    We then look up where that state goes under g.
    """
    return tuple(g[state_to_idx[f[i]]] for i in range(len(f)))


def _is_constant(t: Tuple) -> bool:
    """Check if transformation t is constant (all elements equal)."""
    return len(set(t)) == 1


def is_synchronizing_monoid(A: DFA) -> bool:
    """
    Task (a): Test if DFA A is synchronizing by enumerating the transition monoid.

    Uses BFS over transformations. Returns True if a constant transformation
    is found in T_A, False if the entire monoid is enumerated without finding one.

    Parameters:
        A — a valid DFA 5-tuple

    Returns:
        True if A is synchronizing, False otherwise.

    Warning: Can be extremely slow for large |Q|. The monoid can contain
    up to |Q|^|Q| elements.
    """
    generators, states = _build_generators(A)
    state_to_idx = {s: i for i, s in enumerate(states)}

    # Collect generator transformations
    gen_list = list(generators.values())

    # Check generators themselves
    visited = set()
    queue = deque()
    for t in gen_list:
        if t not in visited:
            if _is_constant(t):
                return True
            visited.add(t)
            queue.append(t)

    # BFS: for each transformation, compose with each generator
    while queue:
        f = queue.popleft()
        for g in gen_list:
            fg = _compose(f, g, states, state_to_idx)
            if fg not in visited:
                if _is_constant(fg):
                    return True
                visited.add(fg)
                queue.append(fg)

    return False
